export enum QUERY_KEYS {
  ADDCHINESERADICAL = 'addchineseradical',
  GETCHINESERADICALS = 'getchineseradicals',
  UPDATECHINESERADICAL = 'updatechineseradical',
  ADDCHINESEIDIOM = 'addchineseidiom',
  GETCHINESEIDIOMS = 'getchineseidioms',
  UPDATECHINESEIDIOM = 'updatechineseidiom',
  GETCHINESEBOOKS = 'getchinesebooks',
  GETCHAPTERSBYBOOKID = 'getchaptersbybookid',
  GETLITERACYBYCHAPTER = 'getliteracybychapter',
  GETHANZISOUND = 'gethanzisound',
  GETHANZIDICTIONARY = 'gethanzidictionary',
  GETHANZIENGLISH = 'gethanzienglish',
  GETHANZIMEANING = 'gethanzimeaning',
  GETWORDSBYCHAPTER = 'getwordsbychapter',
  GETVideoBYCHAPTER = 'getvideobychapter',
  GETCSOLBOOKS = 'getcsolbooks',
  GETSINGBYCHAPTER = 'getsingbychapter',
  GETREADINGBYCHAPTE = 'getreadingbychapter',
  GETAUTH = 'getauth',
  GETCORRECTORDERBYCHAPTER = 'getcorrectorderbychapter',
  ADDCORRECTORDER = 'addcorrectorder',
  DELETECORRECTORDER = 'deletecorrectorder',
}
